### ISSUE TITLE
Dataloader, Train and Evaluation metrics

### ISSUE THREAD

**Issue by aunsid** [GatorSense/PlantRootSeg#2]
Could you provide the code for the dataloader, training and evaluation metrics?

**Comment by weihuangxu** [comment]
Sure. This repo is the demo mainly for the visualization of segmentation results. I can share the code for dataloader, train, and evaluation if you contact me by email.

**Comment by FFQ0112** [comment]
Could you share the code for the dataloader, training and evaluation metrics？
