### ISSUE TITLE
root data 

### ISSUE THREAD

**Issue by Nine9844** [GatorSense/PlantRootSeg#3]
Excuse me. I wonder if it is convenient for you to share all the root data. Thanks

**Comment by weihuangxu** [comment]
Hi. Thanks for your interests in our root data. The root images were collected and owned by our collaborators. We are considering publish the dataset soon.

**Comment by Nine9844** [comment]
> 

That's great. I am waiting for your update, Thank you

**Comment by weihuangxu** [comment]
Hi @Nine9844, FYI, we just published our root dataset. The root images we used in this work is a subset of this published dataset. If you are interested, please access the dataset using this link: https://gatorsense.github.io/PRMI/.

**Comment by Nine9844** [comment]
Dear&nbsp;sir or madam：


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Thank you very much for yo​ur letter. Wish you peace and success in your studies in the New Year.





Best Wishes，

Yunlian





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "GatorSense/PlantRootSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月5日(星期六) 凌晨1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GatorSense/PlantRootSeg] root data  (#3)





 
Hi @Nine9844, FYI, we just published our root dataset. The root images we used in this work is a subset of this published dataset. If you are interested, please access the dataset using this link: https://gatorsense.github.io/PRMI/.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
